#CommonController

ProjectSiteBundle_homepage:
    path:     /
    defaults: { _controller: "ProjectSiteBundle:Common:main" }
    requirements:
         methods:  GET

ProjectSiteBundle_contacts:
    path:     /contacts
    defaults: { _controller: "ProjectSiteBundle:Common:contacts" }
    requirements:
         methods:  GET|POST

#CountryController

ProjectSiteBundle_all_countries:
    path:     /country
    defaults: { _controller: "ProjectSiteBundle:Country:showAll" }
    requirements:
         methods:  GET

ProjectSiteBundle_one_country:
    path:     /country/{id}
    defaults: { _controller: "ProjectSiteBundle:Country:showOne" }
    requirements:
         methods:  GET
         id: \d+

#ProjectSiteBundle_country_create:
#    path:     /administrator/country/create
#    defaults: { _controller: "ProjectSiteBundle:Country:create" }
#    requirements:
#         methods:  GET|POST
#
#ProjectSiteBundle_country_edit:
#    path:     /administrator/country/edit/{id}
#    defaults: { _controller: "ProjectSiteBundle:Country:edit" }
#    requirements:
#         methods:  GET|POST
#         id: \d+
#
#ProjectSiteBundle_country_delete:
#    path:     /administrator/country/delete/{id}
#    defaults: { _controller: "ProjectSiteBundle:Country:delete" }
#    requirements:
#         methods:  GET
#         id: \d+

#CityController

ProjectSiteBundle_all_cities:
    path:     /city
    defaults: { _controller: "ProjectSiteBundle:City:showAll" }
    requirements:
         methods:  GET

ProjectSiteBundle_one_city:
    path:     /city/{id}
    defaults: { _controller: "ProjectSiteBundle:City:showOne" }
    requirements:
         methods:  GET
         id: \d+

#SightController

ProjectSiteBundle_all_sights:
    path:     /sight
    defaults: { _controller: "ProjectSiteBundle:Sight:showAll" }
    requirements:
         methods:  GET

ProjectSiteBundle_one_sight:
    path:     /sight/{id}
    defaults: { _controller: "ProjectSiteBundle:Sight:showOne" }
    requirements:
         methods:  GET
         id: \d+
