<?php

namespace Project\SiteBundle\Entity\Repository;

/**
 * CityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CityRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllOrderedByFullname(){
        $qb=$this->createQueryBuilder('c')->select('c')->innerJoin('c.country','Project\SiteBundle\Entity\Country')->addOrderBy('Project\SiteBundle\Entity\Country.name','ASC')->addOrderBy('c.name','ASC');
        return $qb->getQuery()->getResult();
    }
}
