<?php

namespace Project\SiteBundle\Entity\Repository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends \Doctrine\ORM\EntityRepository
{
        public function findAllOrderedByDate(){
        $qb=$this->createQueryBuilder('c')->select('c')->addOrderBy('c.created','DESC');
        return $qb->getQuery()->getResult();
    }
}
