<?php

namespace Project\SiteBundle\Entity\Repository;

/**
 * PlaceInRouteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlaceInRouteRepository extends \Doctrine\ORM\EntityRepository
{
}
