<?php

namespace Project\SiteBundle\Entity\Repository;

/**
 * PlaceInRouteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlaceInRouteRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByPlace($place_id){
        $qb=$this->createQueryBuilder('p')->select('p')->where('p.place = :place_id')->setParameter('place_id', $place_id);
        return $qb->getQuery()->getResult();
    }
}
