<?php

namespace Project\SiteBundle\Entity\Repository;

/**
 * RoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoleRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByRole($role){
        $qb=$this->createQueryBuilder('r')->select('r')->where('r.role = :role')->setParameter('role', $role);
        return $qb->getQuery()->getSingleResult();
    }
}
