<?php

namespace Project\SiteBundle\Entity\Repository;

/**
 * RouteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RouteRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllOrderedByName(){
        $qb=$this->createQueryBuilder('r')->select('r')->addOrderBy('r.name','ASC');
        return $qb->getQuery()->getResult();
    }
}
