<?php

namespace Project\SiteBundle\Entity\Repository;

/**
 * SightRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SightRepository extends \Doctrine\ORM\EntityRepository
{
}
