<?php
namespace Project\SiteBundle\Entity\Repository;

/**
 * SightRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SightRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllOrderedByFullname(){
        $qb=$this->createQueryBuilder('s')->select('s')->innerJoin('s.city','Project\SiteBundle\Entity\City')->innerJoin('Project\SiteBundle\Entity\City.country','Project\SiteBundle\Entity\Country')->addOrderBy('Project\SiteBundle\Entity\Country.name','ASC')->addOrderBy('Project\SiteBundle\Entity\City.name','ASC')->addOrderBy('s.name','ASC');
        return $qb->getQuery()->getResult();
    }
}
