<?php

namespace Project\SiteBundle\Entity\Repository;

/**
 * TouristInTripRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TouristInTripRepository extends \Doctrine\ORM\EntityRepository
{
     public function findAllOrderedByTrip(){
        $qb=$this->createQueryBuilder('t')->select('t')->addOrderBy('t.trip','ASC');
        return $qb->getQuery()->getResult();
    }
}
