<?php

namespace Project\SiteBundle\Entity\Repository;

/**
 * TripRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TripRepository extends \Doctrine\ORM\EntityRepository
{
        public function findAllOrderedByDate(){
        $qb=$this->createQueryBuilder('t')->select('t')->addOrderBy('t.startDate','DESC');
        return $qb->getQuery()->getResult();
    }

    public function findByRoute($route_id){
        $qb=$this->createQueryBuilder('t')->select('t')->where('t.route = :route_id')->setParameter('route_id', $route_id);
        return $qb->getQuery()->getResult();
    }
}
