<?php

namespace Project\SiteBundle\Entity\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllOrderedByName(){
        $qb=$this->createQueryBuilder('u')->select('u')->addOrderBy('u.username','ASC');
        return $qb->getQuery()->getResult();
    }
}
